jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.11.0
    - run: zig fmt --check src/*.zig
    - run: zig build test
    - run: ./test.sh
name: CI
on:
  pull_request: {}
  push: {}
